CREATE TABLE ROUTES
(
    SERVICE_NAME VARCHAR(20)   UNIQUE NOT NULL,
    IP VARCHAR(30) NOT NULL ,
    PORT INT NOT NULL ,
    LAST_STATUS VARCHAR(40) NOT NULL ,
    CONSTRAINT PK_ROUTES PRIMARY KEY (SERVICE_NAME)
)
;
